version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=5000

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
